- hosts: rspi4
  tasks:

    - name: Update System Package Cache
      apt: update_cache=yes

    - name: Upgrade System Packages
      apt: upgrade=full

    - name: Rebooting if needed...
      command: sudo shutdown -r now removes=/var/run/reboot-required
      async: 0
      poll: 0
      ignore_errors: true
      register: restarted

    - name: Waiting for reboot...
      local_action: wait_for host=localhost port=22 delay=60 state=started
      when: restarted.changed
