- hosts: rspi4
  vars:
    ansible_ssh_timeout: 30
  tasks:

    - name: Update System Package Cache
      become: yes
      become_user: root
      apt: update_cache=yes

    - name: Upgrade System Packages
      become: yes
      become_user: root
      apt: upgrade=full

    - name: Rebooting if needed...
      command: sudo shutdown -r now removes=/var/run/reboot-required
      async: 0
      poll: 0
      ignore_errors: true
      register: restarted

    - name: Waiting for reboot...
      local_action: wait_for host=localhost port=22 delay=60 state=started
      when: restarted.changed

- hosts: hiveos
  vars:
    ansible_ssh_timeout: 30
  tasks:
  
  - name: Selfupgrade
    become: yes
    command: "selfupgrade"
  
  - name: Reboot
    become: yes
    command: "sreboot"
    async: 1
    poll: 0
    ignore_errors: true

- hosts: hiveos
  gather_facts: no
  tasks:
    - name: Wait for the host to come back
      local_action:
        module: wait_for
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 60
        timeout: 300
        state: started
      delegate_to: localhost

- hosts: openwrt
  vars:
    ansible_ssh_timeout: 30
  tasks:
  
  - name: Upgrade System Packages
    shell: |
      opkg update
      opkg list-upgradable | cut -f 1 -d ' ' | xargs -r opkg upgrade

  - name: Reboot
    command: reboot
  
  - name: Waiting for reboot...
    local_action: wait_for host=localhost port=22 delay=60 state=started
